// <auto-generated />
using System;
using HorizonTravel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorizonTravel.Migrations
{
    [DbContext(typeof(HorizonTravelDbContext))]
    partial class HorizonTravelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HorizonTravel.Model.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRezerwacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("LiczbaUczestnikow")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SumarycznaCena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("WycieczkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.HasIndex("WycieczkaId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HorizonTravel.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPlatnosci")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kwota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodaPlatnosci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RezerwacjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RezerwacjaId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HorizonTravel.Model.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("WycieczkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WycieczkaId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("HorizonTravel.Model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentarz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("WycieczkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.HasIndex("WycieczkaId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HorizonTravel.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NazwaRoli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HorizonTravel.Model.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AktualnaCena")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZakonczenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaksymalnaLiczbaMiejsc")
                        .HasColumnType("int");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ZdjecieGlowne")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("Kraj", "AktualnaCena")
                        .HasDatabaseName("IX_Trips_Kraj_AktualnaCena");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("HorizonTravel.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolaId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HorizonTravel.Model.Booking", b =>
                {
                    b.HasOne("HorizonTravel.Model.User", "Uzytkownik")
                        .WithMany("Bookings")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorizonTravel.Model.Trip", "Wycieczka")
                        .WithMany("Bookings")
                        .HasForeignKey("WycieczkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uzytkownik");

                    b.Navigation("Wycieczka");
                });

            modelBuilder.Entity("HorizonTravel.Model.Payment", b =>
                {
                    b.HasOne("HorizonTravel.Model.Booking", "Rezerwacja")
                        .WithMany("Payments")
                        .HasForeignKey("RezerwacjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezerwacja");
                });

            modelBuilder.Entity("HorizonTravel.Model.PriceHistory", b =>
                {
                    b.HasOne("HorizonTravel.Model.Trip", "Wycieczka")
                        .WithMany("PriceHistories")
                        .HasForeignKey("WycieczkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wycieczka");
                });

            modelBuilder.Entity("HorizonTravel.Model.Review", b =>
                {
                    b.HasOne("HorizonTravel.Model.User", "Uzytkownik")
                        .WithMany("Reviews")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorizonTravel.Model.Trip", "Wycieczka")
                        .WithMany("Reviews")
                        .HasForeignKey("WycieczkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");

                    b.Navigation("Wycieczka");
                });

            modelBuilder.Entity("HorizonTravel.Model.User", b =>
                {
                    b.HasOne("HorizonTravel.Model.Role", "Rola")
                        .WithMany("Users")
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rola");
                });

            modelBuilder.Entity("HorizonTravel.Model.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HorizonTravel.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HorizonTravel.Model.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PriceHistories");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("HorizonTravel.Model.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
